# This is heavily based on the featuretools test setup. Most of the setup logic
# is punted to pytest and tox.
#
# See https://github.com/Featuretools/featuretools
#
version: 2
jobs:
  build:
    working_directory: ~/MLBlocks
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: tox
